//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Core/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""StrategyPlayer"",
            ""id"": ""8986ed79-def5-4514-960d-b3a097695e03"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""a32d44e8-de33-44dc-a0ec-12ee79aaaa89"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""68fd236a-b62c-4d35-9ff5-1b02f2fbbd77"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""type"": ""Button"",
                    ""id"": ""05ae669d-fb78-47cd-b959-1f2ed0fc89f9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse1Click"",
                    ""type"": ""Button"",
                    ""id"": ""9fecb683-7c87-40ab-a4a1-b54d49317270"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse2Click"",
                    ""type"": ""Button"",
                    ""id"": ""1d4c2971-f1d3-4ca0-ab00-829d766ab514"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse3Click"",
                    ""type"": ""Button"",
                    ""id"": ""ad89317b-3d1c-49c1-8b4d-b350274fea31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse4Click"",
                    ""type"": ""Button"",
                    ""id"": ""d00f35dc-7ff4-4c4d-b6dc-5b63c83d8e8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse5Click"",
                    ""type"": ""Button"",
                    ""id"": ""1211469e-c2f9-4444-abd0-de2ab6da00e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse3Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""198a4b81-0737-4c52-9e22-aa8b7fb8c9b0"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9b6ec5cf-5759-44f3-9b18-e6a2604183c4"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Move"",
                    ""id"": ""92db7ee3-8dd9-4059-8365-aa73bfc96d71"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""90c44586-5a9d-45fc-aaa0-5edfb5135e93"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""23b220e8-6757-43c3-ba1c-d75b67a62dd5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""345da908-29ca-4c1d-9e24-16d6764235e9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0116add7-0421-47bb-a105-f9fedb573f91"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Rotate"",
                    ""id"": ""b7f109e4-e2c6-44ad-a74f-b686d6e346a5"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""2b03682f-434b-429b-8759-749a2e2967b8"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9d881da8-ba07-43f5-8750-1e1f96f1ee07"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9574408f-2d45-4345-8076-e7f63da49c96"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse1Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56b20296-683b-40a4-bd51-25a1f31d08c7"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse2Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cc16b65-fb5d-427d-97e4-a883eab98dfe"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse3Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e23476e-368d-491c-b71f-af691b464ce3"",
                    ""path"": ""<Mouse>/forwardButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse4Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ead606b-456c-4ce9-adc2-d9edc2f5fb00"",
                    ""path"": ""<Mouse>/backButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse5Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8605fbdf-eb84-470d-b8c6-6b96c3c5bf27"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse3Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // StrategyPlayer
        m_StrategyPlayer = asset.FindActionMap("StrategyPlayer", throwIfNotFound: true);
        m_StrategyPlayer_Jump = m_StrategyPlayer.FindAction("Jump", throwIfNotFound: true);
        m_StrategyPlayer_Move = m_StrategyPlayer.FindAction("Move", throwIfNotFound: true);
        m_StrategyPlayer_Rotate = m_StrategyPlayer.FindAction("Rotate", throwIfNotFound: true);
        m_StrategyPlayer_Mouse1Click = m_StrategyPlayer.FindAction("Mouse1Click", throwIfNotFound: true);
        m_StrategyPlayer_Mouse2Click = m_StrategyPlayer.FindAction("Mouse2Click", throwIfNotFound: true);
        m_StrategyPlayer_Mouse3Click = m_StrategyPlayer.FindAction("Mouse3Click", throwIfNotFound: true);
        m_StrategyPlayer_Mouse4Click = m_StrategyPlayer.FindAction("Mouse4Click", throwIfNotFound: true);
        m_StrategyPlayer_Mouse5Click = m_StrategyPlayer.FindAction("Mouse5Click", throwIfNotFound: true);
        m_StrategyPlayer_Mouse3Scroll = m_StrategyPlayer.FindAction("Mouse3Scroll", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // StrategyPlayer
    private readonly InputActionMap m_StrategyPlayer;
    private List<IStrategyPlayerActions> m_StrategyPlayerActionsCallbackInterfaces = new List<IStrategyPlayerActions>();
    private readonly InputAction m_StrategyPlayer_Jump;
    private readonly InputAction m_StrategyPlayer_Move;
    private readonly InputAction m_StrategyPlayer_Rotate;
    private readonly InputAction m_StrategyPlayer_Mouse1Click;
    private readonly InputAction m_StrategyPlayer_Mouse2Click;
    private readonly InputAction m_StrategyPlayer_Mouse3Click;
    private readonly InputAction m_StrategyPlayer_Mouse4Click;
    private readonly InputAction m_StrategyPlayer_Mouse5Click;
    private readonly InputAction m_StrategyPlayer_Mouse3Scroll;
    public struct StrategyPlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public StrategyPlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_StrategyPlayer_Jump;
        public InputAction @Move => m_Wrapper.m_StrategyPlayer_Move;
        public InputAction @Rotate => m_Wrapper.m_StrategyPlayer_Rotate;
        public InputAction @Mouse1Click => m_Wrapper.m_StrategyPlayer_Mouse1Click;
        public InputAction @Mouse2Click => m_Wrapper.m_StrategyPlayer_Mouse2Click;
        public InputAction @Mouse3Click => m_Wrapper.m_StrategyPlayer_Mouse3Click;
        public InputAction @Mouse4Click => m_Wrapper.m_StrategyPlayer_Mouse4Click;
        public InputAction @Mouse5Click => m_Wrapper.m_StrategyPlayer_Mouse5Click;
        public InputAction @Mouse3Scroll => m_Wrapper.m_StrategyPlayer_Mouse3Scroll;
        public InputActionMap Get() { return m_Wrapper.m_StrategyPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(StrategyPlayerActions set) { return set.Get(); }
        public void AddCallbacks(IStrategyPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_StrategyPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_StrategyPlayerActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Rotate.started += instance.OnRotate;
            @Rotate.performed += instance.OnRotate;
            @Rotate.canceled += instance.OnRotate;
            @Mouse1Click.started += instance.OnMouse1Click;
            @Mouse1Click.performed += instance.OnMouse1Click;
            @Mouse1Click.canceled += instance.OnMouse1Click;
            @Mouse2Click.started += instance.OnMouse2Click;
            @Mouse2Click.performed += instance.OnMouse2Click;
            @Mouse2Click.canceled += instance.OnMouse2Click;
            @Mouse3Click.started += instance.OnMouse3Click;
            @Mouse3Click.performed += instance.OnMouse3Click;
            @Mouse3Click.canceled += instance.OnMouse3Click;
            @Mouse4Click.started += instance.OnMouse4Click;
            @Mouse4Click.performed += instance.OnMouse4Click;
            @Mouse4Click.canceled += instance.OnMouse4Click;
            @Mouse5Click.started += instance.OnMouse5Click;
            @Mouse5Click.performed += instance.OnMouse5Click;
            @Mouse5Click.canceled += instance.OnMouse5Click;
            @Mouse3Scroll.started += instance.OnMouse3Scroll;
            @Mouse3Scroll.performed += instance.OnMouse3Scroll;
            @Mouse3Scroll.canceled += instance.OnMouse3Scroll;
        }

        private void UnregisterCallbacks(IStrategyPlayerActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Rotate.started -= instance.OnRotate;
            @Rotate.performed -= instance.OnRotate;
            @Rotate.canceled -= instance.OnRotate;
            @Mouse1Click.started -= instance.OnMouse1Click;
            @Mouse1Click.performed -= instance.OnMouse1Click;
            @Mouse1Click.canceled -= instance.OnMouse1Click;
            @Mouse2Click.started -= instance.OnMouse2Click;
            @Mouse2Click.performed -= instance.OnMouse2Click;
            @Mouse2Click.canceled -= instance.OnMouse2Click;
            @Mouse3Click.started -= instance.OnMouse3Click;
            @Mouse3Click.performed -= instance.OnMouse3Click;
            @Mouse3Click.canceled -= instance.OnMouse3Click;
            @Mouse4Click.started -= instance.OnMouse4Click;
            @Mouse4Click.performed -= instance.OnMouse4Click;
            @Mouse4Click.canceled -= instance.OnMouse4Click;
            @Mouse5Click.started -= instance.OnMouse5Click;
            @Mouse5Click.performed -= instance.OnMouse5Click;
            @Mouse5Click.canceled -= instance.OnMouse5Click;
            @Mouse3Scroll.started -= instance.OnMouse3Scroll;
            @Mouse3Scroll.performed -= instance.OnMouse3Scroll;
            @Mouse3Scroll.canceled -= instance.OnMouse3Scroll;
        }

        public void RemoveCallbacks(IStrategyPlayerActions instance)
        {
            if (m_Wrapper.m_StrategyPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IStrategyPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_StrategyPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_StrategyPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public StrategyPlayerActions @StrategyPlayer => new StrategyPlayerActions(this);
    public interface IStrategyPlayerActions
    {
        void OnJump(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnRotate(InputAction.CallbackContext context);
        void OnMouse1Click(InputAction.CallbackContext context);
        void OnMouse2Click(InputAction.CallbackContext context);
        void OnMouse3Click(InputAction.CallbackContext context);
        void OnMouse4Click(InputAction.CallbackContext context);
        void OnMouse5Click(InputAction.CallbackContext context);
        void OnMouse3Scroll(InputAction.CallbackContext context);
    }
}
